# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				chicken = true
				cow = true
				tnt_minecart = true
				wolf = true
				pig = true
				bat = true
				chest_minecart = true
				item = true
				squid = true
				sheep = true
				skeleton = true
				zombie = true
				spider = true
				glow_squid = true
				creeper = true
				bee = true
				enderman = true
				witch = true
				salmon = true
				axolotl = true
				zombie_villager = true
				drowned = true
				experience_orb = true
				painting = true
				llama = true
				horse = true
				arrow = true
				slime = true

			[light_sources.settings.entities.handcrafted]
				fancy_painting = true
				seat = true

